In [1]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
pd.options.display.max_rows = 1200
df = pd.read_csv('results_full_17.csv')

import warnings
warnings.filterwarnings("ignore")

In [2]:
# Mostrar todos los DataSets probados. Son 17.
df.dataset.unique()

array(['exist21', 'misogyny_centrogeo', 'davincis22', 'meoffendes21',
       'haha21', 'metwo22', 'mexa3t18_aggress',
       'detoxis21_aggressiveness', 'detoxis21_mockery',
       'detoxis21_sarcasm', 'semeval2018_anger', 'detoxis21_toxicity',
       'misoginia', 'semeval2018_sadness', 'detoxis21_insult',
       'detoxis21_intolerance', 'detoxis21_stereotype'], dtype=object)

In [3]:
len(df.dataset.unique())

17

In [4]:
df_ = df.drop(df.columns[[0,1]],axis=1) # 15 son los 5 k-folds
df_.describe()

# Son 17 DataSets, 9 PreModels repartidos en 50 combinaciones/conjuntos de 3 a 7 elementos + conjunto vacio
# de la columna 0..6 corresponde al correr: train + predict + test 
# de la columna 7 en adelante es la validación cruzada solo con el train
# combinations: arreglo con los PreModels de EvoMSA usados en el training
# combina_1 y combina_2 son los índices del arreglo de PreModels. Es con lo que se enlaza el test y la validacíon cruzada
# en cada renglón, se excluye el PreModel que corresponde al Dataset que esta siendo probado

df_.head()

,dataset,combina_1,train.shape,test.shape,f1,recall,combinations,combina_2,train.shape.1,mean,std,min,max,scores_kfold
0,exist21,0,"(2655, 2)","(886, 2)",0.745956,0.713410,"['detoxis21_aggressiveness', 'haha21', 'mexa3t18_aggress', 'metwo22', 'haha18']",0,"(2655, 2)",0.736086,0.019006,0.713454,0.762691,"[0.7626908234492934, 0.7325790892325152, 0.7189148669340657, 0.7527906604829682, 0.7134539464341503]"
1,exist21,1,"(2655, 2)","(886, 2)",0.742475,0.711430,"['davincis22', 'meoffendes21', 'mexa3t18_aggress', 'haha18']",1,"(2655, 2)",0.734994,0.017877,0.711455,0.756976,"[0.7569759562337466, 0.7269148238131551, 0.724827498083312, 0.7547953964194374, 0.7114550665752715]"
2,exist21,2,"(2655, 2)","(886, 2)",0.743518,0.722669,"['detoxis21_aggressiveness', 'haha21', 'meoffendes21', 'misogyny_centrogeo']",2,"(2655, 2)",0.738015,0.015003,0.722688,0.760662,"[0.760662254005998, 0.7268954509177973, 0.7288049029622063, 0.7510230179028132, 0.7226878217403199]"
3,exist21,3,"(2655, 2)","(886, 2)",0.753738,0.715262,"['detoxis21_aggressiveness', 'haha21', 'metwo22']",3,"(2655, 2)",0.737986,0.017468,0.715304,0.764565,"[0.7645650438946529, 0.7306967984934086, 0.7285969844109379, 0.7507680491551458, 0.7153037420509378]"
4,exist21,4,"(2655, 2)","(886, 2)",0.749332,0.717305,"['davincis22', 'detoxis21_aggressiveness', 'haha21', 'meoffendes21', 'mexa3t18_aggress', 'metwo22']",4,"(2655, 2)",0.736536,0.017016,0.717345,0.760825,"[0.7608252322162599, 0.7269264462311629, 0.7248821826027709, 0.752702774765807, 0.7173447081535317]"

In [5]:
# df_.loc[df['dataset'] == 'meoffendes21'].sort_values(by=['f1'], ascending=False)

In [10]:
ds_final = pd.DataFrame()
df_.rename(columns = {'mean':'media', 'max':'maximo', 'min':'minimo'}, inplace = True)

In [ ]:
for ds_n in df_.dataset.unique():
    _ = df_.loc[df_['dataset'] == ds_n].sort_values(by=['media'], ascending=False)
    empty_value = _.loc[_['combina_1'] == 50].media.iat[0]
    dse = _.loc[(_['media'] > empty_value) | (_['combina_1'] == 50)]    
    dse['diff'] = dse.apply(lambda row: row.media - empty_value, axis=1) 
    dse = dse.loc[dse['diff'] > 0.01]  
    ds_final = pd.concat([ds_final, dse], ignore_index=True)        
ds_final

In [15]:
_ = df_.loc[df_['dataset'] == 'misogyny_centrogeo'].sort_values(by=['f1'], ascending=False)
empty_f1 = _.loc[_['combina_1'] == 50].f1.iat[0]
dse = _.loc[(_['f1'] > empty_f1) | (_['combina_1'] == 50)]    
dse['diff'] = dse.apply(lambda row: row.f1 - empty_f1, axis=1) 
print(empty_f1)
dse
dse[['combina_1']].to_string

0.9000056675233663

<bound method DataFrame.to_string of      combina_1
61          10
67          16
94          43
55           4
89          38
82          31
95          44
63          12
69          18
51           0
86          35
65          14
77          26
87          36
88          37
83          32
84          33
70          19
81          30
76          25
74          23
62          11
97          46
58           7
72          21
90          39
52           1
98          47
78          27
80          29
53           2
71          20
99          48
73          22
91          40
54           3
96          45
85          34
100         49
93          42
59           8
64          13
66          15
68          17
75          24
57           6
92          41
60           9
56           5
79          28
101         50>

In [16]:
_ = df_.loc[df_['dataset'] == 'misogyny_centrogeo'].sort_values(by=['media'], ascending=False)
empty_val = _.loc[_['combina_1'] == 50].media.iat[0]
dse = _.loc[(_['media'] > empty_val) | (_['combina_1'] == 50)]    
dse['diff'] = dse.apply(lambda row: row.media - empty_val, axis=1) 
print(empty_val)
#dse[['combina_1']].to_string
dse

0.8948051010573753

,dataset,combina_1,train.shape,test.shape,f1,recall,combinations,combina_2,train.shape.1,media,std,minimo,maximo,scores_kfold,diff
97,misogyny_centrogeo,46,"(5752, 2)","(1439, 2)",0.904989,0.895692,"['detoxis21_aggressiveness', 'exist21', 'meoffendes21']",46,"(5752, 2)",0.894840,0.009792,0.882475,0.908420,"[0.8824747052817228, 0.9084196906201116, 0.9017213142773681, 0.8852241715399609, 0.8963606586924973]",0.000035
101,misogyny_centrogeo,50,"(5752, 2)","(1439, 2)",0.900006,0.891560,[],50,"(5752, 2)",0.894805,0.010690,0.883503,0.912746,"[0.8852402759260333, 0.9127463721030973, 0.8998756218905473, 0.8835031045058974, 0.8926601308613014]",0.000000

In [ ]:
_ = df_.loc[df_['dataset'] == ds_n].sort_values(by=['media'], ascending=False)
empty_value = _.loc[_['combina_1'] == 50].media.iat[0]
dse = _.loc[(_['media'] > empty_value) | (_['combina_1'] == 50)]    
dse['diff'] = dse.apply(lambda row: row.media - empty_value, axis=1) 
dse = dse.loc[dse['diff'] > 0.01]  
ds_final = pd.concat([ds_final, dse], ignore_index=True)