In [2]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
pd.options.display.max_rows = 2000
df = pd.read_csv('results_full_89.csv')

import warnings
warnings.filterwarnings("ignore")

In [3]:
# Mostrar todos los DataSets probados. Son 17.
df.dataset.unique()

array(['davincis22', 'detoxis21_aggressiveness', 'detoxis21_insult',
       'detoxis21_intolerance', 'detoxis21_mockery', 'detoxis21_sarcasm',
       'detoxis21_stereotype', 'detoxis21_toxicity', 'exist21', 'haha21',
       'meoffendes21', 'metwo22', 'mexa3t18_aggress', 'misoginia',
       'misogyny_centrogeo', 'semeval2018_anger', 'semeval2018_sadness'],
      dtype=object)

In [4]:
len(df.dataset.unique())

17

In [5]:
df.size

22695

In [6]:
df.head()

,Unnamed: 0,dataset,combina_1,train.shape,test.shape,f1,recall,combinations,combina_2,train.shape.1,mean,std,min,max,scores_kfold
0,0,davincis22,0,"(2521, 2)","(841, 2)",0.770816,0.773789,"['exist21', 'meoffendes21', 'misogyny_centrogeo']",0,"(2521, 2)",0.758271,0.015197,0.739703,0.777660,"[0.7497797841885048, 0.7397025171624714, 0.7492108102083143, 0.777660314369175, 0.7749999999999999]"
1,1,davincis22,1,"(2521, 2)","(841, 2)",0.769563,0.775926,"['detoxis21_aggressiveness', 'exist21', 'haha21', 'mexa3t18_aggress']",1,"(2521, 2)",0.760302,0.016210,0.739703,0.781493,"[0.7497797841885048, 0.7397025171624714, 0.7534275997852157, 0.7814927510291749, 0.7771075456888892]"
2,2,davincis22,2,"(2521, 2)","(841, 2)",0.772169,0.775641,['mexa3t18_aggress'],2,"(2521, 2)",0.758638,0.018294,0.735895,0.783409,"[0.7496695307336417, 0.7358951965065501, 0.7473101165085632, 0.7834086712930541, 0.7769084448910741]"
3,3,davincis22,3,"(2521, 2)","(841, 2)",0.774665,0.779915,"['haha21', 'meoffendes21']",3,"(2521, 2)",0.760344,0.016187,0.739703,0.781124,"[0.7517119583387416, 0.7397025171624714, 0.7515227659472955, 0.777660314369175, 0.7811236259467471]"
4,4,davincis22,4,"(2521, 2)","(841, 2)",0.767473,0.767949,"['detoxis21_aggressiveness', 'haha21', 'misogyny_centrogeo', 'metwo22']",4,"(2521, 2)",0.757580,0.013925,0.739703,0.777660,"[0.7539450521815667, 0.7397025171624714, 0.747515068623865, 0.777660314369175, 0.7690753851731735]"

In [7]:
df_ = df.drop(df.columns[[0]],axis=1) # 15 son los 5 k-folds
df_.describe()

# Son 17 DataSets, 9 PreModels repartidos en 50 combinaciones/conjuntos de 3 a 7 elementos + conjunto vacio
# de la columna 0..6 corresponde al correr: train + predict + test 
# de la columna 7 en adelante es la validación cruzada solo con el train
# combinations: arreglo con los PreModels de EvoMSA usados en el training
# combina_1 y combina_2 son los índices del arreglo de PreModels. Es con lo que se enlaza el test y la validacíon cruzada
# en cada renglón, se excluye el PreModel que corresponde al Dataset que esta siendo probado

df_.head()

,dataset,combina_1,train.shape,test.shape,f1,recall,combinations,combina_2,train.shape.1,mean,std,min,max,scores_kfold
0,davincis22,0,"(2521, 2)","(841, 2)",0.770816,0.773789,"['exist21', 'meoffendes21', 'misogyny_centrogeo']",0,"(2521, 2)",0.758271,0.015197,0.739703,0.777660,"[0.7497797841885048, 0.7397025171624714, 0.7492108102083143, 0.777660314369175, 0.7749999999999999]"
1,davincis22,1,"(2521, 2)","(841, 2)",0.769563,0.775926,"['detoxis21_aggressiveness', 'exist21', 'haha21', 'mexa3t18_aggress']",1,"(2521, 2)",0.760302,0.016210,0.739703,0.781493,"[0.7497797841885048, 0.7397025171624714, 0.7534275997852157, 0.7814927510291749, 0.7771075456888892]"
2,davincis22,2,"(2521, 2)","(841, 2)",0.772169,0.775641,['mexa3t18_aggress'],2,"(2521, 2)",0.758638,0.018294,0.735895,0.783409,"[0.7496695307336417, 0.7358951965065501, 0.7473101165085632, 0.7834086712930541, 0.7769084448910741]"
3,davincis22,3,"(2521, 2)","(841, 2)",0.774665,0.779915,"['haha21', 'meoffendes21']",3,"(2521, 2)",0.760344,0.016187,0.739703,0.781124,"[0.7517119583387416, 0.7397025171624714, 0.7515227659472955, 0.777660314369175, 0.7811236259467471]"
4,davincis22,4,"(2521, 2)","(841, 2)",0.767473,0.767949,"['detoxis21_aggressiveness', 'haha21', 'misogyny_centrogeo', 'metwo22']",4,"(2521, 2)",0.757580,0.013925,0.739703,0.777660,"[0.7539450521815667, 0.7397025171624714, 0.747515068623865, 0.777660314369175, 0.7690753851731735]"

In [8]:
# df_.loc[df['dataset'] == 'meoffendes21'].sort_values(by=['f1'], ascending=False)

In [9]:
ds_final = pd.DataFrame()
df_.rename(columns = {'mean':'media', 'max':'maximo', 'min':'minimo'}, inplace = True)

In [10]:
_ = df_.loc[df['dataset'] == 'davincis22'].sort_values(by=['f1'], ascending=False)
empty_f1 = _.loc[_['combina_1'] == 50].f1.iat[0]
empty_media = _.loc[_['combina_1'] == 50].media.iat[0]
#empty_maximo = _.loc[_['combina_1'] == 50].maximo.iat[0]
dse = _.loc[(_['f1'] > empty_f1) | (_['combina_1'] == 50)]    
dse['diff_f1'] = dse.apply(lambda row: row.f1 - empty_f1, axis=1) 
dse['diff_media'] = dse.apply(lambda row: row.media - empty_media, axis=1) 
#dse['diff_maximo'] = dse.apply(lambda row: row.maximo - empty_maximo, axis=1) 
dse.style.background_gradient(cmap ='coolwarm', subset=['diff_f1', 'diff_media'])

In [11]:
corr = dse.corr()
corr.style.background_gradient(cmap ='coolwarm')

In [12]:
for ds_n in df_.dataset.unique():
    _ = df_.loc[df_['dataset'] == ds_n].sort_values(by=['media'], ascending=False)
    empty_value = _.loc[_['combina_1'] == 50].media.iat[0]
    dse = _.loc[(_['media'] > empty_value) | (_['combina_1'] == 50)]    
    dse['diff'] = dse.apply(lambda row: row.media - empty_value, axis=1) 
    dse = dse.loc[dse['diff'] > 0.01]  
    ds_final = pd.concat([ds_final, dse], ignore_index=True)        
ds_final

,dataset,combina_1,train.shape,test.shape,f1,recall,combinations,combina_2,train.shape.1,media,std,minimo,maximo,scores_kfold,diff
0,semeval2018_sadness,37,"(1350, 6)","(641, 6)",0.441982,0.463427,"['davincis22', 'detoxis21_aggressiveness', 'exist21', 'misogyny_centrogeo', 'metwo22']",37,"(1350, 6)",0.481278,0.029213,0.432987,0.516043,"[0.4666290111620419, 0.48778924763159526, 0.5160430398197133, 0.502942668091141, 0.4329872079481898]",0.016399
1,semeval2018_sadness,29,"(1350, 6)","(641, 6)",0.433939,0.472574,"['davincis22', 'exist21', 'meoffendes21', 'misogyny_centrogeo', 'metwo22']",29,"(1350, 6)",0.476666,0.024799,0.444120,0.516350,"[0.4728020157634094, 0.4605266814391304, 0.5163499424062804, 0.48953223816594016, 0.4441201676974035]",0.011787
2,semeval2018_sadness,48,"(1350, 6)","(641, 6)",0.445240,0.489352,"['davincis22', 'misogyny_centrogeo', 'metwo22']",48,"(1350, 6)",0.476297,0.012259,0.456265,0.492814,"[0.47277592855323947, 0.4928138763136177, 0.47533211456818814, 0.4842967175730204, 0.45626464318639204]",0.011417
3,semeval2018_sadness,21,"(1350, 6)","(641, 6)",0.437775,0.478599,"['davincis22', 'exist21', 'haha21']",21,"(1350, 6)",0.475935,0.015158,0.459159,0.502234,"[0.46300608544460997, 0.4788023105211132, 0.5022340882483275, 0.4764749617852114, 0.4591588558500323]",0.011056
4,semeval2018_sadness,34,"(1350, 6)","(641, 6)",0.436629,0.477404,"['davincis22', 'detoxis21_aggressiveness', 'exist21', 'haha21', 'misogyny_centrogeo']",34,"(1350, 6)",0.475496,0.021153,0.447429,0.497836,"[0.447428941019795, 0.49783610903526565, 0.4819171202396455, 0.4964672307113028, 0.4538289078862101]",0.010616
5,semeval2018_sadness,47,"(1350, 6)","(641, 6)",0.440377,0.454659,"['davincis22', 'exist21', 'haha21', 'mexa3t18_aggress', 'misogyny_centrogeo', 'metwo22']",47,"(1350, 6)",0.475265,0.028622,0.428454,0.515660,"[0.46551525143413963, 0.4784835132363422, 0.515659856088169, 0.48820983224185877, 0.4284544736322339]",0.010385
6,semeval2018_sadness,64,"(1350, 6)","(641, 6)",0.438472,0.449538,"['davincis22', 'haha21', 'mexa3t18_aggress', 'metwo22']",64,"(1350, 6)",0.474978,0.033086,0.426300,0.525850,"[0.4615849146676215, 0.49227904394642363, 0.5258504282761332, 0.46887561337796313, 0.4263003383384278]",0.010099
7,semeval2018_sadness,73,"(1350, 6)","(641, 6)",0.442313,0.462989,"['davincis22', 'exist21', 'meoffendes21', 'metwo22']",73,"(1350, 6)",0.474900,0.032962,0.436733,0.531947,"[0.4679392152148094, 0.45159485919890785, 0.531947335410183, 0.4862867553187819, 0.43673299910804914]",0.010021

In [ ]:
_ = df_.loc[df_['dataset'] == 'haha21'].sort_values(by=['f1'], ascending=False)
empty_f1 = _.loc[_['combina_1'] == 50].f1.iat[0]
dse = _.loc[(_['f1'] > empty_f1) | (_['combina_1'] == 50)]    
dse['diff'] = dse.apply(lambda row: row.f1 - empty_f1, axis=1) 
print(empty_f1)
dse
dse[['combina_1']].to_string

In [ ]:
_ = df_.loc[df_['dataset'] == 'misogyny_centrogeo'].sort_values(by=['media'], ascending=False)
empty_val = _.loc[_['combina_1'] == 50].media.iat[0]
dse = _.loc[(_['media'] > empty_val) | (_['combina_1'] == 50)]    
dse['diff'] = dse.apply(lambda row: row.media - empty_val, axis=1) 
print(empty_val)
#dse[['combina_1']].to_string
dse

In [ ]:
_ = df_.loc[df_['dataset'] == ds_n].sort_values(by=['media'], ascending=False)
empty_value = _.loc[_['combina_1'] == 50].media.iat[0]
dse = _.loc[(_['media'] > empty_value) | (_['combina_1'] == 50)]    
dse['diff'] = dse.apply(lambda row: row.media - empty_value, axis=1) 
dse = dse.loc[dse['diff'] > 0.01]  
ds_final = pd.concat([ds_final, dse], ignore_index=True)

In [ ]:
/home/juan.calderon/anaconda3/envs/watermelon/lib/python3.10/site-packages/sklearn/svm/_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(